version: 2.1

jobs:
  build:
    macos:
      xcode: 14.1.0

    steps:
      - checkout
      - run: bundle install
      - run: bundle exec fastlane test

      - store_artifacts:
          path: reports
          destination: slather-reports

workflows:
  sample:
    jobs:
      - build
