default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Run all tests"
  lane :test do
    scan(
      devices: "iPhone 14 Pro Max",
      code_coverage: true
    )
    slather
  end

end
