default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Run all tests"
  lane :test do

    # Tests and gathers code coverage
    scan(
     devices: "iPhone 14 Pro Max",
     code_coverage: true
    )

    # Create the Cobertura XML report
    slather(
     cobertura_xml: true,
     circleci: true
    )

    # Connect to Codecov and upload report
    codecov_reporter

  end

end
